export const RESERVATION_STATUS = {
  PENDING: 'pending',
  CONFIRMED: 'confirmed',
  SEATED: 'seated',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  NO_SHOW: 'no_show',
};

export const RESERVATION_STATUS_LABELS = {
  [RESERVATION_STATUS.PENDING]: 'Kutilmoqda',
  [RESERVATION_STATUS.CONFIRMED]: 'Tasdiqlangan',
  [RESERVATION_STATUS.SEATED]: 'Joylashgan',
  [RESERVATION_STATUS.COMPLETED]: 'Yakunlangan',
  [RESERVATION_STATUS.CANCELLED]: 'Bekor qilingan',
  [RESERVATION_STATUS.NO_SHOW]: 'Kelmadi',
};

export const RESERVATION_STATUS_COLORS = {
  [RESERVATION_STATUS.PENDING]: '#F59E0B',
  [RESERVATION_STATUS.CONFIRMED]: '#3B82F6',
  [RESERVATION_STATUS.SEATED]: '#22C55E',
  [RESERVATION_STATUS.COMPLETED]: '#94A3B8',
  [RESERVATION_STATUS.CANCELLED]: '#EF4444',
  [RESERVATION_STATUS.NO_SHOW]: '#78716C',
};
