/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AloqaRouteImport } from './routes/aloqa'
import { Route as BronRouteImport } from './routes/bron'
import { Route as MenyuRouteImport } from './routes/menyu'
import { Route as RestoranSlugRouteImport } from './routes/restoran.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AloqaRoute = AloqaRouteImport.update({
  id: '/aloqa',
  path: '/aloqa',
  getParentRoute: () => rootRouteImport,
} as any)
const BronRoute = BronRouteImport.update({
  id: '/bron',
  path: '/bron',
  getParentRoute: () => rootRouteImport,
} as any)
const MenyuRoute = MenyuRouteImport.update({
  id: '/menyu',
  path: '/menyu',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoranSlugRoute = RestoranSlugRouteImport.update({
  id: '/restoran/$slug',
  path: '/restoran/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aloqa': typeof AloqaRoute
  '/bron': typeof BronRoute
  '/menyu': typeof MenyuRoute
  '/restoran/$slug': typeof RestoranSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aloqa': typeof AloqaRoute
  '/bron': typeof BronRoute
  '/menyu': typeof MenyuRoute
  '/restoran/$slug': typeof RestoranSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aloqa': typeof AloqaRoute
  '/bron': typeof BronRoute
  '/menyu': typeof MenyuRoute
  '/restoran/$slug': typeof RestoranSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aloqa' | '/bron' | '/menyu' | '/restoran/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aloqa' | '/bron' | '/menyu' | '/restoran/$slug'
  id: '__root__' | '/' | '/aloqa' | '/bron' | '/menyu' | '/restoran/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AloqaRoute: typeof AloqaRoute
  BronRoute: typeof BronRoute
  MenyuRoute: typeof MenyuRoute
  RestoranSlugRoute: typeof RestoranSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aloqa': {
      id: '/aloqa'
      path: '/aloqa'
      fullPath: '/aloqa'
      preLoaderRoute: typeof AloqaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bron': {
      id: '/bron'
      path: '/bron'
      fullPath: '/bron'
      preLoaderRoute: typeof BronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menyu': {
      id: '/menyu'
      path: '/menyu'
      fullPath: '/menyu'
      preLoaderRoute: typeof MenyuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restoran/$slug': {
      id: '/restoran/$slug'
      path: '/restoran/$slug'
      fullPath: '/restoran/$slug'
      preLoaderRoute: typeof RestoranSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AloqaRoute: AloqaRoute,
  BronRoute: BronRoute,
  MenyuRoute: MenyuRoute,
  RestoranSlugRoute: RestoranSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
